-- 生产
NDefines.NProduction.RESOURCE_TO_ENERGY_COEFFICIENT = 1000
NDefines.NProduction.BASE_COUNTRY_ENERGY_PRODUCTION = 1000
NDefines.NProduction.BASE_ENERGY_COST = 0.001
NDefines.NProduction.ENERGY_SCALING_COST_BY_FACTORY_COUNT = 0
NDefines.NBuildings.AIRBASE_CAPACITY_MULT = 2000

-- 无限制租借
NDefines.NDiplomacy.TENSION_CAN_LEND_LEASE = 0
