NDefines.NCountry.REINFORCEMENT_DELIVERY_SPEED_MIN = 1.0
NDefines.NCountry.REINFORCEMENT_EQUIPMENT_DELIVERY_SPEED = 1000.0
NDefines.NCountry.REINFORCEMENT_MANPOWER_DELIVERY_SPEED = 1000.0
NDefines.NCountry.REINFORCEMENT_MANPOWER_CHUNK = 1.0

NDefines.NMilitary.REINFORCEMENT_REQUEST_MAX_WAITING_DAYS = 0
NDefines.NMilitary.REINFORCEMENT_REQUEST_DAYS_FREQUENCY = 0

NDefines.NSupply.RAILWAY_DISTANCE_FACTOR_FOR_REINFORCEMENT_SPEED = 0.0
NDefines.NSupply.TRUCK_DISTANCE_FACTOR_FOR_REINFORCEMENT_SPEED = 0.0
NDefines.NSupply.NAVAL_DISTANCE_FACTOR_FOR_REINFORCEMENT_SPEED = 0.0
