NDefines.NProduction.POWERED_FACTORY_SPEED_MIL = 3.5

NDefines.NMilitary.NAVAL_INVASION_PLANNING_BONUS_MALUS = -1

NDefines.NAI.RESEARCH_AHEAD_BONUS_FACTOR = 4.0
NDefines.NAI.MAX_FUEL_CONSUMPTION_RATIO_FOR_AIR_TRAINING = 0.20

NDefines.NOperatives.AGENCY_UPGRADE_PER_OPERATIVE_SLOT = 3
NDefines.NOperatives.MAX_OPERATIVE_SLOT_FROM_AGENCY_UPGRADES = 2
NDefines.NOperatives.INTEL_NETWORK_STATE_MODIFIER_STRENGTH_THRESHOLD = 10000
NDefines.NOperatives.MAX_RECRUITED_OPERATIVES = 20
